-- 코드를 입력하세요
SELECT DISTINCT(c.CAR_ID) AS CAR_ID
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) c
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%m') = '10'
) h
USING(CAR_ID)
ORDER BY CAR_ID DESC;

===========================================

SELECT DISTINCT(c.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
USING(CAR_ID)
WHERE c.CAR_TYPE = '세단'
AND DATE_FORMAT(START_DATE, '%m') = '10'
ORDER BY c.CAR_ID DESC;