-- 코드를 입력하세요
SELECT
    u.USER_ID, u.NICKNAME,
    SUM(b.PRICE) AS TOTAL_SALES
FROM (
    SELECT USER_ID, NICKNAME
    FROM USED_GOODS_USER
) u
JOIN (
    SELECT WRITER_ID, PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
) b
ON u.USER_ID = b.WRITER_ID
GROUP BY u.USER_ID
HAVING SUM(b.PRICE) >= 700000
ORDER BY TOTAL_SALES;